/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example;

import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author ashto
 */
public class LocalGameInterfacePrototype extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LocalGameInterfacePrototype.class.getName());

    /**
     * Creates new form GameInterfacePrototype
     */
    public LocalGameInterfacePrototype(int playerCount) {
            initComponents();
        
            if (playerCount == 2) {
                p3CardDisplayText.setVisible(false);
                p3CardValue.setVisible(false);
                p4CardDisplayText.setVisible(false);
                p4CardValue.setVisible(false);
            }
            if (playerCount == 3) {
                p4CardDisplayText.setVisible(false);
                p4CardValue.setVisible(false);
        }
            
        SwingUtilities.invokeLater(() -> {
        scaledImageLabel1.setImage(
        new ImageIcon(getClass().getResource("/Uno_Cards-01.png")).getImage());
                
        scaledImageLabel2.setImage(
        new ImageIcon(getClass().getResource("/Uno_Cards-02.png")).getImage());
                
        scaledImageLabel3.setImage(
        new ImageIcon(getClass().getResource("/Uno_Cards-03.png")).getImage());
                
        scaledImageLabel4.setImage(
        new ImageIcon(getClass().getResource("/Uno_Cards-04.png")).getImage());
                
        scaledImageLabel5.setImage(
        new ImageIcon(getClass().getResource("/Uno_Cards-05.png")).getImage());
            
        });
}
                

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackground1 = new org.example.JPanelBackground();
        p3CardValue = new javax.swing.JLabel();
        p4CardDisplayText = new javax.swing.JLabel();
        p3CardDisplayText = new javax.swing.JLabel();
        p2CardDisplayText = new javax.swing.JLabel();
        p4CardValue = new javax.swing.JLabel();
        p2CardValue = new javax.swing.JLabel();
        scaledImageLabel3 = new org.example.ScaledImageLabel();
        scaledImageLabel2 = new org.example.ScaledImageLabel();
        scaledImageLabel4 = new org.example.ScaledImageLabel();
        scaledImageLabel1 = new org.example.ScaledImageLabel();
        scaledImageLabel5 = new org.example.ScaledImageLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p3CardValue.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        p3CardValue.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        p3CardValue.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        p3CardValue.setText("5");

        p4CardDisplayText.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        p4CardDisplayText.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        p4CardDisplayText.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        p4CardDisplayText.setText("Player 4 Cards Remaining:");

        p3CardDisplayText.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        p3CardDisplayText.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        p3CardDisplayText.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        p3CardDisplayText.setText("Player 3 Cards Remaining:");

        p2CardDisplayText.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        p2CardDisplayText.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        p2CardDisplayText.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        p2CardDisplayText.setText("Player 2 Cards Remaining:");

        p4CardValue.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        p4CardValue.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        p4CardValue.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        p4CardValue.setText("5");

        p2CardValue.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        p2CardValue.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        p2CardValue.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        p2CardValue.setText("5");

        javax.swing.GroupLayout jPanelBackground1Layout = new javax.swing.GroupLayout(jPanelBackground1);
        jPanelBackground1.setLayout(jPanelBackground1Layout);
        jPanelBackground1Layout.setHorizontalGroup(
            jPanelBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackground1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBackground1Layout.createSequentialGroup()
                        .addGroup(jPanelBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(p4CardDisplayText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p3CardDisplayText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p2CardDisplayText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p2CardValue, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p3CardValue, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p4CardValue, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelBackground1Layout.createSequentialGroup()
                        .addComponent(scaledImageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scaledImageLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scaledImageLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scaledImageLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scaledImageLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanelBackground1Layout.setVerticalGroup(
            jPanelBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackground1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p2CardDisplayText)
                    .addComponent(p2CardValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p3CardDisplayText)
                    .addComponent(p3CardValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p4CardDisplayText)
                    .addComponent(p4CardValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addGroup(jPanelBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(scaledImageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(scaledImageLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(scaledImageLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(scaledImageLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scaledImageLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBackground1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.example.JPanelBackground jPanelBackground1;
    private javax.swing.JLabel p2CardDisplayText;
    private javax.swing.JLabel p2CardValue;
    private javax.swing.JLabel p3CardDisplayText;
    private javax.swing.JLabel p3CardValue;
    private javax.swing.JLabel p4CardDisplayText;
    private javax.swing.JLabel p4CardValue;
    private org.example.ScaledImageLabel scaledImageLabel1;
    private org.example.ScaledImageLabel scaledImageLabel2;
    private org.example.ScaledImageLabel scaledImageLabel3;
    private org.example.ScaledImageLabel scaledImageLabel4;
    private org.example.ScaledImageLabel scaledImageLabel5;
    // End of variables declaration//GEN-END:variables
}
