/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example;

/**
 *
 * @author ashto
 */
public class PlayInterfacePrototype extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PlayInterfacePrototype.class.getName());

    /**
     * Creates new form PlayMenuPrototype
     */
    public PlayInterfacePrototype() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackground1 = new org.example.JPanelBackground();
        LocalPlayButton = new javax.swing.JButton();
        StoryModeButton = new javax.swing.JButton();
        HardMode = new javax.swing.JRadioButton();
        EasyMode = new javax.swing.JRadioButton();
        BackButton = new javax.swing.JButton();
        playerCountSelector = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LocalPlayButton.setText("Play with Friends");
        LocalPlayButton.addActionListener(this::LocalPlayButtonActionPerformed);

        StoryModeButton.setText("Play Story");
        StoryModeButton.addActionListener(this::StoryModeButtonActionPerformed);

        HardMode.setText("Hard");
        HardMode.addActionListener(this::HardModeActionPerformed);

        EasyMode.setText("Easy");
        EasyMode.addActionListener(this::EasyModeActionPerformed);

        BackButton.setText("Back");
        BackButton.addActionListener(this::BackButtonActionPerformed);

        playerCountSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 Players", "3 Players", "4 Players" }));
        playerCountSelector.setSelectedItem(playerCountSelector);
        playerCountSelector.addActionListener(this::playerCountSelectorActionPerformed);

        javax.swing.GroupLayout jPanelBackground1Layout = new javax.swing.GroupLayout(jPanelBackground1);
        jPanelBackground1.setLayout(jPanelBackground1Layout);
        jPanelBackground1Layout.setHorizontalGroup(
            jPanelBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackground1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBackground1Layout.createSequentialGroup()
                        .addComponent(LocalPlayButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playerCountSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBackground1Layout.createSequentialGroup()
                        .addComponent(StoryModeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EasyMode, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HardMode, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BackButton))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanelBackground1Layout.setVerticalGroup(
            jPanelBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackground1Layout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addGroup(jPanelBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocalPlayButton)
                    .addComponent(playerCountSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StoryModeButton)
                    .addComponent(EasyMode)
                    .addComponent(HardMode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BackButton)
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LocalPlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocalPlayButtonActionPerformed
            String value=(String)playerCountSelector.getSelectedItem(); 
            System.out.println(value);
            
            if("2 Players".equals(value)){
            GameInterfacePrototype GameMenu2 =new GameInterfacePrototype(2);
            GameMenu2.setVisible(true);
            this.dispose();
            }
            
            else if("3 Players".equals(value)){ 
            GameInterfacePrototype GameMenu3 =new GameInterfacePrototype(3);
            GameMenu3.setVisible(true);
            this.dispose();
            }        
            
            else if("4 Players".equals(value)){  
            GameInterfacePrototype GameMenu4 =new GameInterfacePrototype(4);
            GameMenu4.setVisible(true);
            this.dispose();
            }        
    }//GEN-LAST:event_LocalPlayButtonActionPerformed

    private void HardModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HardModeActionPerformed
            HardMode.setSelected(true);
            EasyMode.setSelected(false);
    }//GEN-LAST:event_HardModeActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        MenuInterfacePrototype MainMenu = new MenuInterfacePrototype();
        MainMenu.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonActionPerformed

    private void StoryModeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StoryModeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StoryModeButtonActionPerformed

    
    private void playerCountSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerCountSelectorActionPerformed
           
    }//GEN-LAST:event_playerCountSelectorActionPerformed

    private void EasyModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EasyModeActionPerformed
            HardMode.setSelected(false);
            EasyMode.setSelected(true);
    }//GEN-LAST:event_EasyModeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PlayInterfacePrototype().setVisible(true));
        
        
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JRadioButton EasyMode;
    private javax.swing.JRadioButton HardMode;
    private javax.swing.JButton LocalPlayButton;
    private javax.swing.JButton StoryModeButton;
    private org.example.JPanelBackground jPanelBackground1;
    private javax.swing.JComboBox<String> playerCountSelector;
    // End of variables declaration//GEN-END:variables
}
